[Interface]
# Key for cyber secure
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 4AtiaAyBYmQTCb8bveVuUMefhT2hPf5mU0vx7E0s1Xw=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#114
PublicKey = weCSxoXSpUf0pBwokYIRqxzHNc60zcEthqkNpuCCsWY=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 84.20.27.34:51820

PersistentKeepalive = 25